import {DriverState,faceMetrics} from './engine.mjs';
const $=id=>document.getElementById(id);
const labels={normal:['✓','Tidak ada peringatan','Mata dan kepala terbaca. Tetap perhatikan kondisi Anda.'],calibration:['◎','Kalibrasi pribadi','Lihat lurus, mata terbuka, mulut tertutup selama 4 detik. Kepala perlu stabil.'],no_face:['?','Wajah tidak terbaca','Pastikan hanya satu wajah terlihat penuh, dengan cahaya yang cukup.'],eyes_unknown:['?','Mata tidak dapat dinilai','Pembacaan mata tidak tersedia. Arah kepala tetap dipantau.'],drowsy:['!','Mata tertutup lama','Penutupan kedua mata melewati 1,5 detik. Berhenti di tempat aman dan beristirahat.'],distracted:['!','Kembali fokus ke jalan','Arah kepala melewati batas selama lebih dari 1 detik.'],yawn:['!','Kemungkinan menguap','Mulut terbuka lama terdeteksi. Berbicara juga dapat memengaruhi pembacaan ini.'],fatigue:['!','Indikasi kelelahan','Proporsi mata tertutup meningkat pada waktu yang berhasil diamati.']};
let rules,engine,model,stream,raf,run=0,startedAt=0,kind=null,lastVideoTime=-1,lastFrameAt=0,lastBeep=0,audio,events=[],total=0,renderedStatus='',demoStart=0;
function text(id,value){$(id).textContent=value;}
function resetMetrics(){['ear','pose','perclos'].forEach(id=>text(id,'—'));['eyeBar','poseBar','perclosBar'].forEach(id=>$(id).style.width='0%');text('eyeNote','Menunggu kalibrasi');text('perclosNote','Perlu 20 detik mata terbaca');}
function setStatus(key,detail){const [symbol,title,body]=labels[key]??['—',key,detail];text('statusSymbol',symbol);if(renderedStatus!==title){text('statusTitle',title);renderedStatus=title;}text('statusDetail',detail??body);document.querySelector('.status-panel').dataset.alert=String(['drowsy','distracted','yawn','fatigue'].includes(key));}
function initAudio(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch{}}
function beep(now){if(!$('sound').checked||!audio||now-lastBeep<3)return;lastBeep=now;try{const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.frequency.value=850;gain.gain.setValueAtTime(.07,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);osc.start();osc.stop(audio.currentTime+.35);}catch{}}
function addEvent(event,m){if(event==='drowsy_end')return;total++;events.unshift({time:new Date().toISOString(),event,detail:m?`EAR ${m.ear.toFixed(2)} · yaw ${m.yaw.toFixed(0)}° · pitch ${m.pitch.toFixed(0)}°`:'',source:kind==='demo'?'Simulasi':'Kamera'});events=events.slice(0,500);text('count',total);text('countNote',kind==='demo'?'Termasuk data simulasi':'Peringatan pada sesi ini');$('export').disabled=false;renderEvents();}
function renderEvents(){const body=$('events');body.replaceChildren();for(const ev of events.slice(0,50)){const tr=document.createElement('tr');for(const value of [new Date(ev.time).toLocaleTimeString('id-ID'),labels[ev.event]?.[1]??ev.event,ev.detail,ev.source]){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}}
function render(result,now){setStatus(result.status);$('calibration').hidden=result.status!=='calibration';$('progress').style.width=`${result.progress*100}%`;text('calibrationText',`Kalibrasi ${Math.round(result.progress*100)}%`);const m=result.metrics;text('quality',result.status==='no_face'?'Wajah tidak terbaca':result.status==='calibration'?'Kalibrasi posisi netral':result.eyes_valid?'Mata & kepala terbaca':'Hanya kepala & mulut');if(m){text('ear',result.eyes_valid?m.ear.toFixed(2):'—');text('pose',`${m.yaw.toFixed(0)}° / ${m.pitch.toFixed(0)}°`);text('eyeNote',result.eyes_valid?`Ambang pribadi ${m.threshold.toFixed(2)}`:'Pembacaan mata tidak tersedia');$('eyeBar').style.width=`${result.eyes_valid?Math.min(100,m.ear/.4*100):0}%`;$('poseBar').style.width=`${Math.min(100,Math.max(Math.abs(m.yaw)/rules.yaw_degrees,Math.abs(m.pitch)/rules.pitch_degrees)*50)}%`;}else{resetMetrics();}text('perclos',result.perclos===null?'—':`${Math.round(result.perclos*100)}%`);text('perclosNote',result.perclos===null?`${Math.floor(result.observed_seconds)} / 20 detik mata terbaca`:'Jendela 60 detik · data terbaca');$('perclosBar').style.width=`${(result.perclos??0)*100}%`;for(const ev of result.events)addEvent(ev,m);if(result.active.some(k=>['drowsy','distracted'].includes(k)))beep(now);}
function resetCalibration(){engine=new DriverState(rules,$('glasses').value==='obscured');setStatus('calibration');resetMetrics();$('calibration').hidden=false;demoStart=performance.now()/1000;}
function controls(active){$('start').disabled=active;$('demo').disabled=active;$('stop').disabled=!active;$('calibrate').disabled=!active;}
function stop(message='Sesi dihentikan',detail='Kamera telah dimatikan. Riwayat dapat diunduh sebelum Anda menutup halaman.') {run++;cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());stream=null;$('video').srcObject=null;kind=null;controls(false);$('placeholder').hidden=false;$('placeholder').querySelector('h3').textContent='Siap saat Anda siap';$('placeholder').querySelector('p').textContent='Posisikan kamera sejajar mata, lalu mulai sesi monitoring.';$('demoTag').hidden=true;$('calibration').hidden=true;text('cameraStatus','Nonaktif');text('mode','SESI BERAKHIR');text('quality','Kamera nonaktif');text('fps','— FPS');resetMetrics();setStatus(message,detail);}
async function loadRules(){if(!rules){const response=await fetch('./rules.json');if(!response.ok)throw Error('Aturan deteksi gagal dimuat.');rules=await response.json();}}
async function loadModel(){if(model)return;const {FaceLandmarker,FilesetResolver}=await import('./vendor/vision_bundle.mjs');const vision=await FilesetResolver.forVisionTasks('./vendor/wasm');model=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'./vendor/face_landmarker.task',delegate:'CPU'},runningMode:'VIDEO',numFaces:2,minFaceDetectionConfidence:.7,minFacePresenceConfidence:.7,minTrackingConfidence:.7,outputFacialTransformationMatrixes:true});}
async function start(demo=false){const token=++run;controls(true);initAudio();setStatus('Menyiapkan sesi',demo?'Menyiapkan simulasi berlabel.':'Memuat detektor. Pada pemakaian pertama, unduhan model dapat memerlukan waktu.');try{await loadRules();if(token!==run)return;if(!demo){if(!navigator.mediaDevices?.getUserMedia)throw Error('Kamera membutuhkan HTTPS dan browser yang mendukung akses kamera.');await loadModel();if(token!==run)return;setStatus('Menunggu izin kamera','Detektor siap. Izinkan kamera pada permintaan browser, atau pilih Hentikan.');const acquired=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});if(token!==run){acquired.getTracks().forEach(t=>t.stop());return;}stream=acquired;stream.getVideoTracks()[0].addEventListener('ended',()=>{if(token===run)stop('Kamera terputus','Mulai kamera kembali untuk melanjutkan.');});$('video').srcObject=stream;await $('video').play();if(token!==run)return;}
kind=demo?'demo':'camera';startedAt=performance.now()/1000;lastVideoTime=-1;lastFrameAt=performance.now();total=0;events=[];text('count','0');text('countNote','Belum ada peringatan');$('events').innerHTML='<tr><td colspan="4" class="empty">Belum ada kejadian pada sesi ini.</td></tr>';$('export').disabled=true;$('placeholder').hidden=!demo;$('demoTag').hidden=!demo;if(demo){$('placeholder').querySelector('h3').textContent='Simulasi perilaku';$('placeholder').querySelector('p').textContent='Kalibrasi → menoleh → mata tertutup → pulih';}else{$('placeholder').querySelector('h3').textContent='Siap saat Anda siap';$('placeholder').querySelector('p').textContent='Posisikan kamera sejajar mata, lalu mulai sesi monitoring.';}text('cameraStatus',demo?'Simulasi':'Aktif');text('mode',demo?'SESI SIMULASI':'SESI KAMERA');resetCalibration();loop(token);
}catch(error){if(token!==run)return;const message=error.name==='NotAllowedError'?'Izin kamera ditolak. Izinkan kamera melalui pengaturan situs, lalu coba lagi.':error.name==='NotFoundError'?'Kamera tidak ditemukan. Hubungkan kamera lalu coba lagi.':error.name==='NotReadableError'?'Kamera sedang dipakai aplikasi lain. Tutup aplikasi tersebut lalu coba lagi.':error.message;stop('Sesi belum dimulai',message);}}
function loop(token){if(token!==run||!kind)return;const now=performance.now()/1000,elapsed=Math.floor(now-startedAt);text('timer',`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`);try{if(kind==='demo'){const t=now-demoStart;let m={ear:.3,left_ear:.3,right_ear:.3,mar:.1,yaw:0,pitch:0,roll:0};if(t>6&&t<9)m.yaw=32;if(t>11&&t<14){m.ear=.13;m.left_ear=.13;m.right_ear=.13;}render(engine.update(m,now),now);text('fps','SIMULASI');if(t>18)demoStart=now-5;}else{const video=$('video');if(video.readyState>=2&&video.currentTime!==lastVideoTime){lastVideoTime=video.currentTime;const at=performance.now();const results=model.detectForVideo(video,at);const m=faceMetrics(results,video.videoWidth,video.videoHeight);text('fps',`${Math.min(60,Math.round(1000/Math.max(1,at-lastFrameAt)))} FPS`);lastFrameAt=at;render(engine.update(m,at/1000),now);}else if(performance.now()-lastFrameAt>700){render(engine.update(null,now),now);text('quality','Tidak ada frame kamera baru');}}}catch(error){stop('Deteksi terhenti','Pembacaan kamera gagal. Coba mulai kembali atau gunakan browser lain.');return;}raf=requestAnimationFrame(()=>loop(token));}
$('start').addEventListener('click',()=>start(false));$('demo').addEventListener('click',()=>start(true));$('stop').addEventListener('click',()=>stop());$('calibrate').addEventListener('click',()=>{if(rules&&kind)resetCalibration();});$('glasses').addEventListener('change',()=>{if(rules&&kind)resetCalibration();});$('sound').addEventListener('change',initAudio);
$('export').addEventListener('click',()=>{const quote=v=>'"'+String(v).replaceAll('"','""')+'"';const csv='\uFEFF'+[['timestamp','event','detail','source'],...events.map(e=>[e.time,e.event,e.detail,e.source])].map(row=>row.map(quote).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`driver-session-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&$('stop').disabled===false)stop('Sesi dijeda','Tab tidak aktif. Mulai sesi kembali saat halaman terbuka agar pembacaan tetap berkesinambungan.');});window.addEventListener('pagehide',()=>{run++;cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());});
